# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 250)
        MainWindow.setMinimumSize(QtCore.QSize(500, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main ico/images/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmMain = QtWidgets.QFrame(self.centralwidget)
        self.frmMain.setMinimumSize(QtCore.QSize(0, 200))
        self.frmMain.setStyleSheet("")
        self.frmMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMain.setObjectName("frmMain")
        self.gridLayout = QtWidgets.QGridLayout(self.frmMain)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.txeOutput = QtWidgets.QTextEdit(self.frmMain)
        self.txeOutput.setStyleSheet("")
        self.txeOutput.setReadOnly(True)
        self.txeOutput.setObjectName("txeOutput")
        self.gridLayout.addWidget(self.txeOutput, 10, 2, 1, 1)
        self.psbStart = QtWidgets.QPushButton(self.frmMain)
        self.psbStart.setEnabled(True)
        self.psbStart.setMinimumSize(QtCore.QSize(90, 0))
        self.psbStart.setAutoFillBackground(False)
        self.psbStart.setStyleSheet(":enabled {\n"
" color:  rgb(225, 225, 225);\n"
"background-color: rgb(0, 124, 195);\n"
"}\n"
"\n"
":disabled {\n"
" color:  rgb(120, 120, 120);\n"
" background-color: rgb(204, 204, 204);\n"
"}")
        self.psbStart.setAutoDefault(False)
        self.psbStart.setDefault(False)
        self.psbStart.setFlat(False)
        self.psbStart.setObjectName("psbStart")
        self.gridLayout.addWidget(self.psbStart, 10, 1, 1, 1)
        self.lblHint = QtWidgets.QLabel(self.frmMain)
        self.lblHint.setMinimumSize(QtCore.QSize(0, 20))
        self.lblHint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblHint.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblHint.setObjectName("lblHint")
        self.gridLayout.addWidget(self.lblHint, 1, 2, 1, 1)
        self.lnePath = QtWidgets.QLineEdit(self.frmMain)
        self.lnePath.setEnabled(True)
        self.lnePath.setReadOnly(True)
        self.lnePath.setObjectName("lnePath")
        self.gridLayout.addWidget(self.lnePath, 6, 2, 1, 1)
        self.psbBrowse = QtWidgets.QPushButton(self.frmMain)
        self.psbBrowse.setEnabled(True)
        self.psbBrowse.setObjectName("psbBrowse")
        self.gridLayout.addWidget(self.psbBrowse, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.psbAbout = QtWidgets.QToolButton(self.frmMain)
        self.psbAbout.setEnabled(True)
        self.psbAbout.setMinimumSize(QtCore.QSize(100, 27))
        self.psbAbout.setMaximumSize(QtCore.QSize(100, 27))
        self.psbAbout.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.psbAbout.setFocusPolicy(QtCore.Qt.NoFocus)
        self.psbAbout.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.psbAbout.setAcceptDrops(False)
        self.psbAbout.setToolTip("")
        self.psbAbout.setStatusTip("")
        self.psbAbout.setWhatsThis("")
        self.psbAbout.setAccessibleName("")
        self.psbAbout.setAccessibleDescription("")
        self.psbAbout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.psbAbout.setAutoFillBackground(True)
        self.psbAbout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/garmin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.psbAbout.setIcon(icon1)
        self.psbAbout.setIconSize(QtCore.QSize(100, 27))
        self.psbAbout.setShortcut("")
        self.psbAbout.setAutoRepeat(False)
        self.psbAbout.setAutoExclusive(False)
        self.psbAbout.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.psbAbout.setAutoRaise(True)
        self.psbAbout.setArrowType(QtCore.Qt.NoArrow)
        self.psbAbout.setObjectName("psbAbout")
        self.gridLayout.addWidget(self.psbAbout, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frmMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actAbout = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actAbout.setIcon(icon2)
        self.actAbout.setObjectName("actAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Garmin message replacer 1.0"))
        self.psbStart.setText(_translate("MainWindow", "START\n"
"replacing"))
        self.lblHint.setText(_translate("MainWindow", "Please, select desired language file to replace messages:"))
        self.psbBrowse.setText(_translate("MainWindow", "Browse ..."))
        self.actAbout.setText(_translate("MainWindow", "About"))
        self.actAbout.setToolTip(_translate("MainWindow", "About"))
from . import resources_rc
